name:       'CSE 510'
baseurl:    '/courses/cse510/16wi'

brandimage: ''
brandtext:  'CSE 510 - Advanced Topics in HCI - Winter 2016'

lessc: node_modules/.bin/lessc

navbar:
  items:
    - text: 'Home'
      link: 'index.html'
    - text: 'Calendar'
      link: 'calendar.html'

exclude:
  # Bootstrap
  - bootstrap/less
  # Node
  - node_modules
  - npm-shrinkwrap.json
  - package.json
  # Python
  - env34
  - env35
  - requirements3.txt
  - tasks.py
  - tasks.pyc
  # README
  - README.md
  # Ruby
  - Gemfile
  - Gemfile.lock
  # Tests
  - tests

collections:
  assignments:
    output: true
